# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
url: https://tianqi.name #!the base hostname & protocol for your site e.g. https://www.someone.com (!!required!!)
baseurl: /jekyll-TeXt-theme
title: Someone's blog
description: > #this means to ignore newlines until "nav_lists:"
  Someone's Blog

nav_lists:
  # - title: About
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

## GitHub repository (if the site is hosted by GitHub) ##
repository: kitian616/jekyll-TeXt-theme
repository_tree: master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai

## Author & social ##
author:
  name: Someone
  email: someone@somemail.com  #your Email address e.g. someone@site.com
  facebook: someone  #your Facebook username
  twitter: someone  #your Twitter username
  github: someone  #your GitHub username
  googleplus: someone  #your Google+ username
  weibo: someone  #your Weibo username
  douban: someone  #your Douban username
  linkedin: someone  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html ## text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - README.md
  - LICENSE
  - /vendor
  - /docs
  - /screenshots
  - /test

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false