# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

# config file for development, DELETE IT IF YOU WANT.

text_color_theme: default #eg: default | dark | forest | ocean | chocolate | orange
## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com

baseurl: /
title: Someone's blog
description: > #this means to ignore newlines until "nav_lists:"
  Someone's Blog

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html
  - title: Baidu
    url: https://www.baidu.com

paths:
  # base: /
  # home: /
  # all:  /all.html
  # rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: someone/someone.github.io
repository_tree: master

## Language & timezone ##
# lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: Someone
  email: someone@somemail.com  #your Email address e.g. someone@site.com
  facebook: someone  #your Facebook username
  twitter: someone  #your Twitter username
  github: someone  #your GitHub username
  googleplus:   #your Google+ username
  weibo:   #your Weibo username
  douban:   #your Douban username
  linkedin:   #your Linkedin username

## TOC
toc:
  # selectors: 'h1,h2,h3,h4,h5,h6'

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: 143666b578a416f82175 #Github Application Client ID
  clientSecret: 1d1c0604a1a4bff9b59ab7f56724dc0e8b837775 #Github Application Client Secret
  repository: gitalk-demo #Github repo
  owner: kitian616 #Github repo owner
  admin:  #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - kitian616

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true
# mathjax_autoNumber: true
# mermaid: true
# chart: true

## Paginate ##
paginate: 3
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Sources ##
# sources: bootcss #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  # - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"