# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Base settings ##
base_url: https://www.someone.com # **required!** The site's Protocol and Hostname e.g. https://blog.someone.com
base_path: '/'
title: Someone's blog
description: > #this means to ignore newlines until "nav_lists:"
  Someone's Blog

nav_lists:
  - title: About
    url: /about.html

## GitHub repository (if the site is hosted by GitHub) ##
# github_repo: e.g. someone.github.io
# github_repo_tree: e.g. master

## Language & timezone ##
lang: zh #the language of your site
timezone: Asia/Shanghai

## Author & social ##
author: Someone
email: someone@mail.com #your Email address e.g. someone@site.com
facebook_username: someone #your Facebook username
twitter_username: someone #your Twitter username
github_username: someone #your GitHub username
googleplus_username: someone #your Google+ username
weibo_username: someone #your Weibo username
douban_username: someone #your Douban username
linkedin_username: someone #your Linkedin username

## Comment system (Disqus) ##
# disqus_shortname:  #the Disqus shortname for the site

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
# app_id:  #LeanCloud App id
# app_key:  #LeanCloud App key
# app_class:  #LeanCloud App class

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false