version: "3.5"

services:
  jekyll-text-theme_build:
    image: docker_jekyll-text-theme_dev
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    container_name: jekyll-text-theme_build
    volumes:
      - ..:/usr/src/app
    command: bundle exec jekyll build
  jekyll-text-theme_web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    container_name: jekyll-text-theme_web
    restart: unless-stopped
    volumes:
      - ../_site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jekyll-text-theme_build